<?php
/**
 * @file
 * Code for the FB Safety General feature.
 */

include_once 'fb_safety_general.features.inc';


function fb_safety_general_data_filter_number($data) {
  return intval($data);
}

function fb_safety_general_data_filter_text($data) {
  return $data;
}

function fb_safety_general_data_filter_from_id($data) {
  return $data['id'];
}

function fb_safety_general_data_filter_time($data) {
  return strtotime($data);
}
